# Generated by Django 5.1.4 on 2024-12-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journey',
        ),
    ]
