# Generated by Django 5.1.4 on 2024-12-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
