# Generated by Django 5.1.4 on 2024-12-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0004_alter_journey_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='maps_link',
            field=models.CharField(default='value', max_length=255),
            preserve_default=False,
        ),
    ]
