# Generated by Django 5.1.4 on 2024-12-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0005_journey_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='budget_breakdown',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='maps_link',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='name_of_location',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='journey',
            name='wellbeing_impact',
            field=models.CharField(),
        ),
    ]
